version: "3"
virtualmachines:
  - name: server
    image: ubuntu-os-cloud/ubuntu-2204-lts
    shell: /bin/bash
    machine_type: n1-standard-1
  - name: node-a
    image: ubuntu-os-cloud/ubuntu-2204-lts
    shell: /bin/bash
    machine_type: e2-standard-2
  - name: node-b
    image: ubuntu-os-cloud/ubuntu-2204-lts
    shell: /bin/bash
    machine_type: e2-standard-2
  - name: node-c
    image: ubuntu-os-cloud/ubuntu-2204-lts
    shell: /bin/bash
    machine_type: e2-standard-2
  - name: node-d
    image: ubuntu-os-cloud/ubuntu-2204-lts
    shell: /bin/bash
    machine_type: e2-standard-2